### ISSUE TITLE
Damaged libjni_notifications.so

### ISSUE THREAD

**Issue by elect86** [zoff99/jni_notifications#4]
As titled, when I try to run `main`, I get

> java.lang.UnsatisfiedLinkError: /home/elect/IdeaProjects/jni_notifications/libjni_notifications.so: /home/elect/IdeaProjects/jni_notifications/libjni_notifications.so: file too short
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2418)
	at java.base/java.lang.Runtime.load0(Runtime.java:852)
	at java.base/java.lang.System.load(System.java:2025)
	at com.zoffcc.applications.jninotifications.NTFYActivity.jninotifications_loadjni(NTFYActivity.java:135)
	at com.zoffcc.applications.jninotifications.NTFYActivity.main(NTFYActivity.java:151)
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'java.lang.String com.zoffcc.applications.jninotifications.NTFYActivity.jninotifications_version()'
	at com.zoffcc.applications.jninotifications.NTFYActivity.jninotifications_version(Native Method)
	at com.zoffcc.applications.jninotifications.NTFYActivity.main(NTFYActivity.java:158)
	
According to [this](https://unix.stackexchange.com/a/523497), the library file should be damaged

I also get this

> OpenJDK 64-Bit Server VM warning: You have loaded library /home/elect/IdeaProjects/jni_notifications/libjni_notifications.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
2024-04-10_15:40:42.584:1:4:NTFYActivity:loadLibrary libjni_notifications failed! path: /home/elect/IdeaProjects/jni_notifications/./libjni_notifications.so

**Comment by elect86** [comment]
After running `elect@5800x:~/IdeaProjects/jni_notifications$ ./tools/update_jni_notifications_jni_libs.sh`, it works flawless, thanks!

**Comment by elect86** [comment]
I do see "title"/"message" and then "4b"/"4c" right away, I see none of these

```
        jninotifications_notify(null,
            null, null,
            null);
        try{Thread.sleep(s);}catch(Exception e){}

        jninotifications_notify(null,
            "1b", "1c",
            "1d");
        try{Thread.sleep(s);}catch(Exception e){}

        jninotifications_notify("2a",
            null, "2c",
            "2d");
        try{Thread.sleep(s);}catch(Exception e){}

        jninotifications_notify("3a",
            "3b", null,
            "3d");
        try{Thread.sleep(s);}catch(Exception e){}
```

**Comment by zoff99** [comment]
> I do see "title"/"message" and then "4b"/"4c" right away, I see none of these
> 
> ```
>         jninotifications_notify(null,
>             null, null,
>             null);
>         try{Thread.sleep(s);}catch(Exception e){}
> 
>         jninotifications_notify(null,
>             "1b", "1c",
>             "1d");
>         try{Thread.sleep(s);}catch(Exception e){}
> 
>         jninotifications_notify("2a",
>             null, "2c",
>             "2d");
>         try{Thread.sleep(s);}catch(Exception e){}
> 
>         jninotifications_notify("3a",
>             "3b", null,
>             "3d");
>         try{Thread.sleep(s);}catch(Exception e){}
> ```

thats fine. those with ```null``` should not show. it is only to test that it does not produce a native crash when given null strings

**Comment by zoff99** [comment]
ahh yes libjni_notifications.so has zero byte size, thanks for reporting this. there must have been a mistake on the last push

**Comment by elect86** [comment]
Great lib!

Ps: btw, if you want, I can provide a PR with Gradle, where the libs will be automatically downloaded
Also a Kotlin translation for some code conciseness, if you like

**Comment by zoff99** [comment]
no need for download. i will fix the lib

**Comment by zoff99** [comment]
ok, can you please try now without downloading the libs. just the repo.
also in what project do you want to use it?

**Comment by elect86** [comment]
Also some publication would be nice for easier the consumption of the lib for the users

I'm gonna use it in a little program with a tray icon for connecting to [Hzdr](https://www.hzdr.de/) vpn

I'll give you credits :)

**Comment by elect86** [comment]
> ok, can you please try now without downloading the libs. just the repo.

Yep, now it works fine

**Comment by zoff99** [comment]
@elect86 
_"Also some publication would be nice for easier the consumption of the lib for the users"_
if you want to make a PR, that would be highly appreciated

**Comment by elect86** [comment]
Ok, credits [given](https://github.com/elect86/easnx/blob/master/README.md)

Could you add me to the repo so that I don't need to fork it? I'll work on another branch

**Comment by zoff99** [comment]
sorry i cant add anyone to me personal repo. but you can send me any diffs and i put them in, if this works better for you.

**Comment by elect86** [comment]
would you be interested into automatizing the lib creation part as well?

**Comment by zoff99** [comment]
sure. only thing i want is that it can still be used like now, meaning to just copy the .java and .so files into a project like now. anything else optional on top of that is welcome.
or if you mean the creating of the JNI lib, that is automated already. the only thing that github CI does not support is the macos arm JNI lib. its built on https://codemagic.io/. if you know anyway to build that on gitbub CI or linux in general i would be happy to include that.

**Comment by elect86** [comment]
is your project public? Is it using Gradle?

Il giorno dom 14 apr 2024 alle ore 19:24 Zoff ***@***.***> ha
scritto:
